# This file was generated by GoReleaser. DO NOT EDIT.
cask "redactr-community" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "e5603610378d76f97d34bceac92374696117cfb1f0c378e0b04b8ab0a12e5f65"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1006c8eaa7212ac4fff5a05d40502a8ef0e88a1f6198cb94c77905d0312c0d62"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0ea637937f2b94bfc5011a307cc61ee7638f22f66bcb5291737b473dd39c280c"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0e065de0161551c837e20de8da014ca0c6461cc1a2bc4fc3960df19356d695e"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_linux_arm64.tar.gz"
    end
  end

  name "redactr-community"
  desc "Regex-only redaction proxy — Redactr community edition"
  homepage "https://redactrai.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redactr-community"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redactr-community"]
    end
  end

  # No zap stanza required

end
