# This file was generated by GoReleaser. DO NOT EDIT.
cask "redactr" do
  version "0.3.2"

  on_macos do
    on_intel do
      sha256 "687ebff0b19057b32dd454537f12be648a809df37c523765501c165e954189c4"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ec96c380d367571fad7526410931de0fdfcfcf8c3b4bc679efd15324f38141e7"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "248077d889096835868ce17efbb5e76233a7db0db5367243a3342faf7f8b1462"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2138b75abf27e3089dac7bcbf9c2b0a7d90e5e721d6caf6bb225ba7bf326e9cb"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "redactr"
  desc "Regex-only redaction proxy — Redactr community edition"
  homepage "https://redactrai.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redactr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redactr"]
    end
  end

  # No zap stanza required

end
