# This file was generated by GoReleaser. DO NOT EDIT.
cask "redactr" do
  version "0.3.3"

  on_macos do
    on_intel do
      sha256 "a6cf888d123f50685a2a8557358a7307331a4eea7c633682db628bf2ecf1dbea"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a15b56ab478eb7e195a70e24eb1f0332645efee2c3a8ced6e1d0dda0fe6b3407"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "f198d85732bb288f4c689972037492d9be506a146973e2de9a702cbf58efccf0"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "272b8a56b81551ca4e2de3a8199a0c8c234704b81612ed62eb6e8bb6d8d17665"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "redactr"
  desc "Regex-only redaction proxy — Redactr community edition"
  homepage "https://redactrai.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redactr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redactr"]
    end
  end

  # No zap stanza required

end
