# This file was generated by GoReleaser. DO NOT EDIT.
cask "redactr-community" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "6f0e0f593e5d0a0f0d1710769c32160352434ad30ec21cc02a131d5ba84e9536"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8067b9e5ff266e07bb465c25e85062614b5740162ab7b1f2fe1e592361a480a8"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "aa6e222204190e0f576c8e71a490a69f707de9b51103227c2ec913a2b692ae72"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "4831ad8e0018e9a098ad8d0dafa05c302ea458651b8c6bf9f733cf6c9d637856"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr-community_#{version}_linux_arm64.tar.gz"
    end
  end

  name "redactr-community"
  desc "Regex-only redaction proxy — Redactr community edition"
  homepage "https://redactrai.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redactr-community"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redactr-community"]
    end
  end

  # No zap stanza required

end
