# This file was generated by GoReleaser. DO NOT EDIT.
cask "redactr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "95e1206ce9339d3973c0a2737059f50edae73674082363b79253a0206157940b"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0fd55519f033ce0ceeb7ad7ddc6db48dd60c3b52bc700d1ecbbe9431b2d93e78"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef175196e3bd1f09988e89d5b45f4769072a89e750b3daed5ab9018814cd9cec"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2f0d29768677c5f19f6dd5ae68b836a496e05a3f678aada133505f59d692c6fe"
      url "https://github.com/redactrai/redactr-community/releases/download/v#{version}/redactr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "redactr"
  desc "Regex-only redaction proxy — Redactr community edition"
  homepage "https://redactrai.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "redactr"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/redactr"]
    end
  end

  # No zap stanza required

end
